services:
  publisher:
    environment:
      EXIST_VERSION: "{{exist_version|default('6.2.0')}}"
      NER_ENDPOINT: http://ner:8001
      CONTEXT_PATH: "" # TEI Publisher will be mapped to the root of the website
    {% if application.image %}
    image: {{application.image}}:{{application.version}}
    {% else %}
    build:
      context: {{application.repository}}#{{application.version}}
      dockerfile: {{application.dockerfile}}
      args:
        {% for key, value in application.args.items() %}
        {{key}}: {{value}}
        {% endfor %}
    {% endif %}
    # comment in to automatically restart:
    restart: always
    volumes:
      # database files will be stored in a volume to avoid data loss
      # when the service is updated
      - /exist/data
      # uncomment to map eXist-db backups to local directory
      # - ./backup:/exist/backup
    {% if ner %}
    depends_on:
      - ner
  ner:
    # image will be pulled from github
    image: ghcr.io/eeditiones/tei-publisher-ner/teipublisher-ner:master
    # enable if you want to build from source:
    # build:
    #   context: https://github.com/eeditiones/tei-publisher-ner.git#master
    #   dockerfile: Dockerfile
    # comment in to automatically restart:
    restart: always
  {% endif %}
  frontend:
    image: nginx:alpine
    volumes:
      - ./conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - publisher
    # comment in to automatically restart:
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw